<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/assets/images/favicon.ico" type="image/x-icon">

    <title>Error</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <style>
        body {
            background-color: #001f3f;
        }

        .modal-content {
            background-color: #001f3f;
            color: #ffffff;
            border: 2px solid gray;
            border-radius: 10px;
        }
    </style>

</head>

<body>
    <div class="container mt-5">
        <span id="errorIcon" class="bi bi-exclamation-triangle"></span>
        <div class="modal fade show d-flex justify-content-center align-items-center" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true" style="display: block;">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="errorModalLabel"><span class="text-danger">Oops, something went wrong!</span></h5>
                        <a href="/" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></a>
                    </div>
                    <div class="modal-body">
                        <p>Sorry, there was an error on the server. Here are the details:</p>
                        <hr>
                        <p class="mb-0">
                            <?php
                            if (isset($errorDetails)) {
                                echo '<strong>Error Message:</strong> '.$errorDetails['message'].'<br>';
                                echo '<strong>File:</strong> '.$errorDetails['file'].'<br>';
                                echo '<strong>Line:</strong> '.$errorDetails['line'].'<br>';
                                echo '<strong>Status Code:</strong> '.$errorDetails['status_code'].'<br>';
                                echo '<strong>Trace:</strong> '.$errorDetails['trace'].'<br>';
                            } else {
                                echo 'Error details not available.';
                            }
                            ?>
                        </p>
                    </div>
                    <div class="modal-footer">
                        <a href="/" class="btn btn-primary">Go Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
