<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error 404 - Page Not Found</title>
    <link rel="shortcut icon" href="/assets/images/favicon.ico" type="image/x-icon">
    <meta name="description" content="The page you are looking for was not found.">
    <meta name="author" content="Yan Brasiliano Silva Penalva">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/css/style.css">
    <style>
      body {
        background-color: #001f3f; 
      }
      .container {
        height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }
      h1 {
        font-size: 4rem;
        color: #ffffff;
        margin-bottom: 1rem;
      }
      p {
        font-size: 1.5rem;
        margin-bottom: 2rem;
        color: #ffffff;
      }
    </style>
  </head>
  <body>
    <div class="container text-center">
      <h1 class="display-4">Error 404 - Page Not Found</h1>
      <p class="lead">The page you are looking for was not found.</p>
      <a href="/" class="btn btn-primary">Go to Home</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>
